# -*- coding: utf-8 -*-
"""PythonInit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFaby_5D0HCkjBAZiL3p02EdGDBfmLk9
"""

x = 'salt'

if x>1:
    print("Greater")
elif x<1:
    print("Smaller")
elif x==1:
    print("Equal")
else:
    print("Invalid")

'''
def thing():
  print('New Func')
  print('Func Executed')

thing()
print('Pause')
thing()
print('Exit')

'''
big = max('Helloz world')
print('Big is',big)

tiny = min('aHello world')
print('Small is',tiny)

for i in [1,2,3,4,5]:
  print(i)
print('Exit Loop')


friends = ['Jimmy','Creta','Virtus']

for friends in friends:
  print("Hello",cars)
print('exit this loop')

"""#***Finding smallest and largest number from multiple inputs and terminating at done as input***"""

#finding smallest and largest number from multiple inputs and terminating at done as input

largest = None
smallest = None

while True:
    user_input = input("Enter an integer number or 'done' to finish: ")

    if user_input.lower() == 'done':
        break

    try:
        num = int(user_input)
        if largest is None or num > largest:
            largest = num
        if smallest is None or num < smallest:
            smallest = num
    except ValueError:
        print("Invalid input")

if largest is not None and smallest is not None:
    print("Maximum is", largest)
    print("Minimum is", smallest)
else:
    print("No valid numbers entered.")

"""# **Searching through a File**"""

fhand = open('mbox.txt')
for line in fhand:
  if line.startswith('From:'):
    print(line)

#used rstrip to remove whitespaces
fhand = open('mbox.txt')
for line in fhand:
  if line.startswith('From:'):
    print(line.rstrip())

#Another way of doing the same thing but in different way:

fhand = open('mbox.txt')
for line in fhand:
  if not line.startswith('From:'):
    continue
  print(line.rstrip())